/* ──────────────────────────────────────────
   Model: SavedZonalAudit
   Standalone saved zonal audit generated by AI.
   One per coordinator per month.
   ────────────────────────────────────────── */
import mongoose, { Schema, Document, Model, Types, models } from "mongoose";
import type { IZonalAuditReport } from "@/types/zonal-audit";

export interface ISavedZonalAudit extends Document {
    coordinator: Types.ObjectId;
    zoneName: string;
    month: string; // e.g., "2025-08"
    auditData: IZonalAuditReport;
    createdAt: Date;
    updatedAt: Date;
}

const SavedZonalAuditSchema = new Schema<ISavedZonalAudit>(
    {
        coordinator: { type: Schema.Types.ObjectId, ref: "Coordinator", required: true, index: true },
        zoneName: { type: String, required: true },
        month: { type: String, required: true },
        auditData: { type: Schema.Types.Mixed, required: true },
    },
    { timestamps: true }
);

// One saved zonal audit per coordinator per month
SavedZonalAuditSchema.index(
    { coordinator: 1, month: 1 },
    { unique: true }
);

export const SavedZonalAudit: Model<ISavedZonalAudit> =
    models.SavedZonalAudit || mongoose.model<ISavedZonalAudit>("SavedZonalAudit", SavedZonalAuditSchema);
